# Generated by Django 4.1.5 on 2023-01-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namaz_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Namaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.namaz_times')),
            ],
        ),
    ]
