# Generated by Django 4.1.5 on 2023-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_namaz_times_namaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='namaz_times',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
