# Generated by Django 4.1.5 on 2023-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_namaz_times_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namaz',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Namaz_times',
        ),
    ]
